language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - wget http://dl.google.com/android/repository/sysimg_armv7a-15_r02.zip
  - mkdir ~/builds/joelbyler/ADB/android-sdk-linux/system-images/android-15
  - unzip sysimg_armv7a-15_r02.zip -d ~/builds/joelbyler/ADB/android-sdk-linux/system-images/android-15
  # setup your ANDROID_HOME and PATH environment variables
  # use ~/builds/[Github username]/[project]/android-sdk-linux
  - export ANDROID_HOME=~/builds/joelbyler/ADB/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - android list sdk --all
  - android update sdk -u -f --filter 1,2
  - android list sdk --all
  - android update sdk -u -f --filter 6,33 --force
  - android list sdk --all
  #- android list sdk --all
  #- android update sdk --filter 1,3,6,31,32,35 --no-ui --force
  #- android update sdk -u --filter platform,tool,extra,platform-tools,android-15,extra-android-support  
  #- android update sdk -u -f --filter android-13 
  - android update sdk -u -f --filter android-15
  #- android update sdk -u -f --filter 33
  #- android list sdk --all
  - android list target
  - echo no | android create avd -n Android_4.0.3 -t 1 --force
  - emulator -avd Android_4.0.3 -port 5554 -no-window -no-audio -no-boot-anim &
  - adb wait-for-device

language: ruby
rvm:
  - 1.9.3

#after_script:
#  - bundle exec rake test